name = "category_theory"
version = "1.0.0"

authors = ["VSebastian8"]
description = "Category theory concepts in gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "VSebastian8", repo = "Category-Theory" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
